### ISSUE TITLE
Replacing font awesome with inline svg

### ISSUE THREAD

**Issue by Rafi993** [bryphe/oni#149]
Font awesome is good but oni does not use all of it awesomeness wouldnt it be better if we could use https://dmfrancisco.github.io/react-icons/  instead of font awesome reducing file size

**Comment by extr0py** [comment]
I'm open to a replacement - I'm sure there are better icons too for the completion than the ones I chose from fontawesome! It looks like the react-icons project has a pretty small set of icons, though.

I saw this project: http://fontello.com/

This has a compilation of icons across projects, and let you build a font that only includes the icons you need - looks pretty cool

**Comment by bryphe** [comment]
Looking at this again - I'm closing for now, since there isn't a clear benefit to switching at this time. The file size isn't our current "bottleneck" for our package size. If someone is up for taking a pass at this, though, it would be awesome to have a more refined set of SVGs eventually.
