### ISSUE TITLE
Custom githpages

### ISSUE THREAD

**Issue by Rafi993** [bryphe/oni#165]
Would it be nice if custom gitpages was created for this repo

**Comment by extr0py** [comment]
Good idea. I've hooked it up to have a page at https://extr0py.github.io/oni - will hook up some of the documentation to it later.

**Comment by bert88sta** [comment]
Hey @extr0py, I'd be happy to maintain this. If there's something I'm actually good at, it's writing. I'd be happy to fill this up with features and goals :)

**Comment by extr0py** [comment]
Sweet, that would be great @bert88sta :) Our documentation could definitely use some help! I'm working on just having it hooked up to the README.md for now, but it'd be nice to have something a bit more high-level for the github page.

**Comment by bryphe** [comment]
I'd like to create a full-fledged website shortly, so I'll close this out
