### ISSUE TITLE
Background color with "artifacts"

### ISSUE THREAD

**Issue by xangelux** [bryphe/oni#170]
The background color has "artifacts" and change while scrolling:

![screenshot 2017-01-17 16 59 19](https://cloud.githubusercontent.com/assets/1622554/22043801/fbe7f846-dcd6-11e6-9401-c582d90734c1.png)

**Comment by extr0py** [comment]
Thanks for the report, @xangelux . Which colorscheme are you using?

**Comment by xangelux** [comment]
I was trying to use Molokai but I see it doesn't take it, it flickers when I open oni and then back to the default one

**Comment by extr0py** [comment]
Unfortunately I'm not able to repro this (although I'm only testing on Windows & Linux) - perhaps its an OSX specific rendering issue?

**Comment by extr0py** [comment]
I poked around a bit and set `colorcolumn=80` and changed to `Monokai` colorscheme, and I do see a few rendering irregularities on Windows:
![image](https://cloud.githubusercontent.com/assets/13532591/22176903/a4559102-dfc8-11e6-9a99-4ea48b66edec.png)

Could potentially be related

**Comment by bryphe** [comment]
Not seeing this reproduce anymore (and the rendering strategy has changed a few times since this was opened!). Please feel free to reopen or log a new issue if you are still seeing this.
