### ISSUE TITLE
Feature: set line height

### ISSUE THREAD

**Issue by metalelf0** [bryphe/oni#173]
Hi all, I know this might be complicated due to the current Grid implementation, but I think it would be really nice if we could set a line height option to give more air to text.

Maybe [this PR on NyaoVim](https://github.com/rhysd/NyaoVim/issues/19) could give some hints.

Thanks!

**Comment by extr0py** [comment]
Thanks for the suggestion, @metalelf0 !

I think we could potentially add this by factoring in the line-height when we measure the font, and making sure the text is vertically centered within that line (which should happen for free by setting the line-height css property). The cursor size would also need to be addressed - it is sized with font size, so would encompass the entire line. We could potentially handle this by doing a separate measurement (one with line-height, one without - the latter being to size the cursor). Seems doable though, and the PR you linked to is definitely helpful

**Comment by justinmk** [comment]
Note that the `'linespace'` option exists for this, and `OptionSet` autocmd could be used by frontends to handle changes to it.

**Comment by extr0py** [comment]
Ah, cool, thanks @justinmk  - didn't know about that option. I'll read up on `:help linespace` and investigate leveraging that.
