### ISSUE TITLE
Better support asynchronous operations in Ctrl-P / QuickOpen

### ISSUE THREAD

**Issue by bryphe** [bryphe/oni#269]
Currently, we wait until the operation is totally complete before we show results in Ctrl-P / QuickOpen.

It'd be nice though if we show results as we get them, like the Ctrl-P implementation in VSCode.

We'd need to modify our events somewhat:
- Signal the start of menu population (show loading spinner)
- SIgnal additional results (add results, keep loading spinner)
- Signal that all results have been added (remove loading spinner)

And add a UI affordance (have an `isLoading` value in the store, and hook that up to our react components)

The nice thing about this is `Ctrl-P` would feel very responsive, even when there is a large traversal of the file system.

**Comment by cyansprite** [comment]
I will look into this.
