### ISSUE TITLE
Mouse wheel in Logs area scrolls both Neovim and Logs

### ISSUE THREAD

**Issue by keforbes** [bryphe/oni#373]
Using the mouse wheel in Neovim scrolls the file but using the mouse wheel in Logs scrolls both Logs *and* Neovim.

![mouse_wheel](https://cloud.githubusercontent.com/assets/817509/25104649/5dc224c2-237e-11e7-9a57-09256dc9a3ef.gif)

**Comment by extr0py** [comment]
Thanks for catching this, @keforbes . Seems like we need to rationalize the way we are handling the scroll event - I think we just put it on the `document.body`, but for the editor itself, we should be listening to the root element.

**Comment by bryphe** [comment]
This is not need anymore, but should be taken  into account with #699
