### ISSUE TITLE
Language Client: Implement signature help

### ISSUE THREAD

**Issue by bryphe** [bryphe/oni#378]
Implement signature help functionality: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_signatureHelp

**Comment by extr0py** [comment]
Based on what the language server protocol gives us for this, the signature help UI might need to be restyled.

The typescript language service gives us separator characters for each parameter. However, the language server just gives the function name, a description, and argument info. A better format for representing that might be a bulleted list, and the selected argument can be highlighted.
