### ISSUE TITLE
Add ability to record videos & screenshots directly in Oni

### ISSUE THREAD

**Issue by bryphe** [bryphe/oni#416]
Based on the Electron desktopCapture APIs, and gif creation libraries, it should be relatively straightforward to add the ability within Oni to capture animated gifs. This would be really nice for bug repros, and to leverage with Spectron/automation to create the demo gifs automatically.

**Comment by bryphe** [comment]
Gif shot looks like a cool library for this

**Comment by bryphe** [comment]
Testing using `gifshot` resulted in poor quality, unfortunately. For now, I'll constrain this to writing video (.webm) and screenshots (.png).

**Comment by keforbes** [comment]
Will you be creating an animated gif demonstrating this behavior for the README/wiki ?

**Comment by bryphe** [comment]
Yep, I'll add something in Wiki (in the configuration section). I was thinking of adding a "Tips" or "Recipes" section, and  show how to bind a key to take a screenshot. 

I'm planning on pushing a new release out Monday as well - so I'll call out it there in the release notes too.

**Comment by bryphe** [comment]
I'll also add some documentation around these new APIs:
`oni.recorder.startRecording()`
`oni.recorder.stopRecording()`
`oni.recorder.takeScreenshot()`

And new configuration options:
`recorder.outputPath`
`recorder.copyScreenshotToClipboard`

**Comment by bryphe** [comment]
Added some API documentation here:
https://github.com/bryphe/oni/wiki/API

And an example of binding a key to use the `takeScreenshot` method here:
https://github.com/bryphe/oni/wiki/Configuration

**Comment by bryphe** [comment]
I'll close this out, but the documentation is still pretty rough (and it would be nice to have some examples or tips/tricks)
