### ISSUE TITLE
Can't move over tabs when using virtualedit

### ISSUE THREAD

**Issue by Uroc327** [bryphe/oni#447]
`set virtualedit=all` makes it impossible in `normal` and `visual` mode, to move over a tab (`^I`) to the right. Moving over a tab from the left works completely fine.
Also moving over the tab in `insert` mode seems to work.

**Comment by extr0py** [comment]
Looks like it could be related to #399 - seems like we have a whole class of issues around `virtualedit=all`

**Comment by Uroc327** [comment]
Apparently this is fixed. Setting `virtualedit=all` the cursor can be moved over tabs in any direction or mode.

**Comment by bryphe** [comment]
Excellent. Thanks for the confirmation, @Uroc327 !
