### ISSUE TITLE
Oni open binaries will cause crash

### ISSUE THREAD

**Issue by gynet** [bryphe/oni#473]
If a user uses Oni to open a binary, e.g Oni.exe, node.dll in the package, it will crash within seconds.

**Comment by extr0py** [comment]
Thanks for logging the issue! I'm assuming you're on Windows?

I'm able to reproduce as well on Windows 10. It looks like Oni gets the `disconnect` even from Neovim (which I believe means the neovim process died).

This doesn't reproduce in `nvim-qt.exe` - so I'm wondering if it is related to the default / core set of plugins we use for Oni integration. In particular, the buffer update might be causing problems for these large binary files.

**Comment by gynet** [comment]
Yes, I am using Windows 10

**Comment by keforbes** [comment]
Interesting, this isn't a problem on Linux; it loads binary files just fine.  I tried with nvim.exe, which is 3.8MB so I don't think large file sizes are a problem.  I wonder if this issue only occurs on Windows.

**Comment by cyansprite** [comment]
I will look into this too since I am making a plugin and it sometimes opens very, very large files :).
