### ISSUE TITLE
cmd+q doesn't quit

### ISSUE THREAD

**Issue by endlist** [bryphe/oni#483]
On MacOS, the expected behavior for all apps is that Cmd+Q will fully close an app, including open windows.  This doesn't work for Oni, I have to either right click on the icon in the dock or use the menu bar to fully quit.

**Comment by bert88sta** [comment]
Keyboard.tsx has a block of code I wrote that discards all command prefixed
key chords. As of right now we're not sure if there's going to be a
configuration value or if we'll whitelist certain common non-vim bindings
