### ISSUE TITLE
Completion dropdown gets hidden when on bottom

### ISSUE THREAD

**Issue by badosu** [bryphe/oni#577]
There should be a mechanism to recalculate it's y position if called from the bottom or something else to keep being usable.

![2017-08-07-172216_869x165_scrot](https://user-images.githubusercontent.com/347552/29044320-490b9544-7b95-11e7-906f-6265e8373bff.png)

**Comment by extr0py** [comment]
Thanks for logging the issue, @badosu !

This is related to the popover issue in #526 too (for QuickInfo). The positioning determination should be generalized, and leveraged for both autocompletion and quickinfo.

In the case you showed where autocompletion is hitting the bottom, it should open upwards so it isn't clipped.
