### ISSUE TITLE
Can't input special characters on international keyboard layout

### ISSUE THREAD

**Issue by lbebber** [bryphe/oni#638]
I can't input characters such as `~`, `"`, etc., on my computer (macOS 10.12).

My keyboard is the regular Apple US Layout keyboard, but it's configured with the U.S. International layout, so in order to type, say, a ~ character, I type `~` + `<space>`. Oni seems to simply ignore the first key.

**Comment by extr0py** [comment]
Thanks for logging the issue, @lbebber ! Looks like there are a few issues to resolve in terms of keyboard layouts - we also have #396 which is similiar (but for Windows IME).

The way we are listening to key events and translating them to vim-keys in `Keyboard.ts` might not be sufficient in this case.

**Comment by lbebber** [comment]
If I may suggest, you could look into what https://github.com/zeit/hyper does for text input—if I'm not mistaken it had the same problem once, and it's also an Electron app.

**Comment by justjoeyuk** [comment]
@extr0py Specifically, this file seems of interest: https://github.com/zeit/hyper/blob/7a08b1dc3e07ae552debfe7e62c48b0a5a028ff9/lib/utils/key-code.js

**Comment by bryphe** [comment]
Fixed in PR #716 and in the latest release [v0.2.10](https://github.com/bryphe/oni/releases/tag/v0.2.10-recovery), so I'll close this. Let me know if you're still seeing any issues, though!
