### ISSUE TITLE
alt key doesn't seem to work

### ISSUE THREAD

**Issue by Alok** [bryphe/oni#696]
Pretty much the title. commands like `<a-s>` work in iterm but not in oni

**Comment by extr0py** [comment]
Hi Alok, thanks for logging the issue!

I wasn't able to repro this on Windows, but I'm able to reproduce it on OSX using this command:
` :noremap <a-s> :echo "test"<CR>`

Seems like we're not handling the alt key properly or something here, there must be some difference in our input processing in `Keyboard.ts`

**Comment by extr0py** [comment]
Somewhat related to #644 - <a-s> resolves to the `ß` character on OS X, so we may need some handling to differentiate that (it's kind of similar to the AltGr issue, just in the general case) - our current input code gives us `<a-ß>`, which isn't going to be what nevoid expects.

**Comment by Alok** [comment]
One way around this is to use Ukelele and unmap all unicode dead keys. i did that and it works now. but that's such a nuisance.

**Comment by extr0py** [comment]
Thanks for the update @Alok . Hopefully that will help others running into this. 

>  but that's such a nuisance.

Agree 100%! These input blockers are top-of-mind for me to tackle next.

**Comment by bryphe** [comment]
This is fixed in the latest release (0.2.10) - <a-s> should resolve correctly to ß on OS X, without needing to use Ukulele. LMK if you're still seeing it, after upgrading. Thanks!
