### ISSUE TITLE
Adjust height of the statusBar

### ISSUE THREAD

**Issue by badosu** [bryphe/oni#713]
On a high DPI display the statusbar is almost illegible. See:

![screenshot from 2017-09-18 14-28-51](https://user-images.githubusercontent.com/347552/30555408-dd8e654e-9c7d-11e7-9aa8-c7102dfbf0db.png)

**Comment by extr0py** [comment]
Interesting... I have a High DPI display on Windows that behaves differently, but it might be auto-scaling up the pixels.

I believe the issue here is by default `px` is being used for font-sizes. It may be better to use `pt` for the core font rendering + `em` for the UI pieces.

**Comment by bryphe** [comment]
This should be fixed now (actually with PR #714, since that introduced `em` sizing vs `px` for the statusbar).

In addition, there is also a `statusbar.fontSize` setting that can be used if there are still issues.

I'll close this, but let me know if you're still seeing issues here. Thanks!

**Comment by badosu** [comment]
@bryphe The font is indeed adjustable, and for my case I was able to make it look a little better:

![screenshot from 2017-10-10 08-36-51](https://user-images.githubusercontent.com/347552/31384667-46ced074-ad96-11e7-8c98-98514d5f104f.png)

However the statusbar height does not scale with the font size, so that's what you get without any configuration:

![screenshot from 2017-10-10 08-35-45](https://user-images.githubusercontent.com/347552/31384702-6b44e1d2-ad96-11e7-88e6-7e355b201fbf.png)

I'd suggest reopening this issue to fix the height scaling of the statusbar or adding a configuration option to manually set it. I can also take a look at it later on.

**Comment by bryphe** [comment]
Brought in #780 - hopefully this is fixed completely now. Feel free to reopen if you're still seeing it, @badosu .

**Comment by badosu** [comment]
@bryphe It's fixed, thank you very much!

The only issue is that now the status bar scales the height more quickly than the font-size, probably a matter of taste.

If required as a new issue I'll file to customize the statusbar height.
