### ISSUE TITLE
How add .vimrc or sysinit.vim config for oni?

### ISSUE THREAD

**Issue by DemonCloud** [bryphe/oni#734]

**Comment by bryphe** [comment]
Hi @DemonCloud ,

Did you set the `oni.loadInitVim` to configuration value to true?  

Check out the this question on the FAQ:  [Why isn't my init.vim loaded?](https://github.com/bryphe/oni/wiki/FAQ#why-isnt-my-initvim-loaded) for some more info.

I'll close this for now, but feel free to re-open if that doesn't answer your question.
