### ISSUE TITLE
Dead keys do not work on command mode

### ISSUE THREAD

**Issue by lbebber** [bryphe/oni#746]
The [dead key issue](https://github.com/bryphe/oni/issues/638) seems to have been fixed for the text editor (great job, by the way), but I still can't input them on `:` commands, which is a blocker for me.

**Comment by lbebber** [comment]
They also do not work for normal commands, e.g. `'` to move to a mark, `"` to use a register, `^` to go to the start of the line, `~` to switch the case of a letter.

Perhaps this should be a different issue, but I do not know how to name this issue hahah. "Dead keys do not work for commands"?

**Comment by lbebber** [comment]
The vim/nvim behaviour in this last case, by the way, is to treat the dead key input as usual, i.e., `"`+`i` runs an nonexistent `í` command—to use the `i` register I need to type `"`+`<space>`+`i`.

**Comment by badosu** [comment]
Can confirm this on 0.2.10

**Comment by bryphe** [comment]
Ah, so close. Thanks for testing it out, @lbebber ! 

Glad things are working better in insert mode. Seems like there are two issues:
- Dead keys aren't working in normal mode (thanks for calling out the Vim behavior, that's very helpful!)
- Dead keys aren't working in cmdline mode

I'll check it out in a bit. Today, in non-insert mode, the `KeyboardInput` code falls back to just handling keydowns, but that isn't sufficient for handling dead keys - so might need some extra logic there. I think it should be straightforward to fix though (just the platforms have different ways of signaling dead keys, which is annoying!)

**Comment by lbebber** [comment]
Thanks @bryphe—as far as I know this is the only issue that prevents me from using Oni, and I'm really looking forward to it.
