### ISSUE TITLE
[BUG]: Oni should respect path that is captured with vim commands

### ISSUE THREAD

**Issue by someguynamedmatt** [bryphe/oni#756]
I noticed that if I run the standard vim command to change directories `:e ~/code/whatever`, Oni correctly changes to that directory, but when I run the Oni-specific command to browse those folders (after having run the vim command) `<CTRL>P` it doesn't reflect that I'm in my newly-entered directory.

Feel free to delete this if it's a repeat of a currently documented bug/issue.

MacOS Sierra 10.12.5
Oni 0.2.11

**Comment by bryphe** [comment]
Hi @someguynamedmatt ,

Right now, Oni defaults to whatever the working folder Neovim has for the quickopen UI.

You can get the behavior you want though by adding this setting to your Oni config:
`'vim.setting.autochdir': true,`

(alternatively, if you want to customize via your `init.vim`, you can add the line `set autochdir`).

With this set, whenever you edit a file, Neovim will change the working directory, and then gets pushed up to Oni.

I hope that helps! I'll close this for now, but feel free to re-open if that doesn't fix the issue.
