### ISSUE TITLE
VS Code Presets

### ISSUE THREAD

**Issue by CrossR** [bryphe/oni#770]
Hey,

Am I mistaken or were the VS Code presets not updated when the main code moved to typescript?
That is, the two debugging profiles in the .vscode folder.
I get errors for each as they are looking for main.js in the root directory of the oni git dir.

I've updated them to `{WorkspaceRoot}/lib/main/src/main.js` and they both seem to work now.

Is this just me and a weird environment thing?
Or if its needed, in the main repo I can submit a PR.

Cheers

**Comment by bryphe** [comment]
Hi @CrossR ,

Thanks for catching this! Yes, this is a mistake - unfortunately I missed updating this when I migrated the main process code to typescript. It would be great to have that `launch.json` updated, to make it easy to debug the main process. 

If you'd be up for submitting a PR, that would be great! Sounds like you've already fixed it locally.

**Comment by CrossR** [comment]
Just submitted a PR for this now! 

Just wanted to check I wasn't going crazy.
I had a few issues getting the initial build to work again after bringing in the keyboard input changes, so I wasn't sure if it was just me.

(If anyone cares, it was because I had Python 3.6 installed, and node-gyp wanted 2.7. Then when I fixed that, I was missing a valid version of MS Build so I used the fix outlined at the bottom of here to get a valid version of MS Build https://github.com/chjj/pty.js/issues/60)

**Comment by bryphe** [comment]
Thanks for submitting the fix, and for the notes about the build issues! Just merged it in.

FYI - I updated this wiki page: [Development](https://github.com/bryphe/oni/wiki/Development). For windows, microsoft released an npm module called `windows-build-tools`. It actually installs both `MSBuild` and `python 2.7` for building node-gyp modules. But sounds like you already have a working setup anyway. Feel free to edit though if we can improve/simplify anywhere.
