### ISSUE TITLE
Overlapping syntax / compilation errors

### ISSUE THREAD

**Issue by TalAmuyal** [bryphe/oni#782]
I'm sure it is a known issue, but I think it should be logged.

When having more then one syntax/compilation errors on the same line (and the cursor is on that line), the tool-tips usually overlap which makes it really hard to read.

**Comment by bryphe** [comment]
Ah ya, thanks for making sure this is tracked, @TalAmuyal ! Definitely an annoying issue.

One option I'm exploring is listing the errors in the same UI that we show the hover / quick-info results... I'll put a screenshot up once I have a working prototype.

**Comment by TalAmuyal** [comment]
Thanks!
Looks neat.
