### ISSUE TITLE
Quit doesn't cause the application to quit in OSX

### ISSUE THREAD

**Issue by MikaAK** [bryphe/oni#788]
I'm using the latest version of Oni (have reinstalled twice to confirm) and have noticed CMD-Q doesn't cause the application to quit as expected but rather the current window to close. Using `remote.app.quit()` causes the actual app to quit instead of just closing the window 😄 
PR: #787

**Comment by bryphe** [comment]
Ah, nice catch, thanks @MikaAK ! And appreciate you putting a PR together.

**Comment by bryphe** [comment]
Fixed by your PR - #787 😄
