### ISSUE TITLE
Auto complete list and closed buffers

### ISSUE THREAD

**Issue by CrossR** [bryphe/oni#809]
It looks like the auto complete list isn't updated when files are closed.

This means that if you open a file to look at the bit of code you need say, and then close the file, the auto complete is then filled with extra suggestions which may not be relevant anymore.

**Comment by bryphe** [comment]
Hi @CrossR ,

Interesting - a couple of questions:
- What file type does this repro for? Is it like javascript, typescript or something else?
- Are you using any completion plugins?

It could be a few different things depending on the manifestation (for example, whether we're using an integrated language server or the Neovim popupmenu).

**Comment by CrossR** [comment]
I'm now unable to repro this, so its possible it was an issue with my config...

I'll close for now and can always re-open if it happens again and I can repro it reliably.

**Comment by bryphe** [comment]
Sounds good, let me know if you see it again. Knowing the filetype will help. I'm in the midst of revamping some of the completion / language service functionality right now.

I think for JavaScript files, the TypeScript language service sometimes caches tokens from opened javascript files - that could be related too if it was JavaScript or TypeScript.
