### ISSUE TITLE
Override Electron menu with new menu

### ISSUE THREAD

**Issue by bryphe** [bryphe/oni#81]
Would be nice to have a custom menu, with some options like:
- Edit config.json
- Edit keybindings.json

As well as expose some of the IDE-level functionalities:
- Go-to definition
- etc..

In developer mode, we'd of course want to preserve the developer toolbar

**Comment by extr0py** [comment]
PR #147 by @Rafi993  gives us a framework to make this much easier!

**Comment by CameronDiver** [comment]
In addition is there currently a way to hide the menubar? I didn't see any configuration for it, and I think it'd be a good options.

**Comment by keforbes** [comment]
There currently isn't a way to hide the menubar but that should be a pretty straightforward config option.  I'll see what I can do.

**Comment by bryphe** [comment]
Doesn't look like there is any action need here - will use new issues to track changes in the menubar.
