### ISSUE TITLE
OSX - Not scroll bar or cursorline in correct window

### ISSUE THREAD

**Issue by Bretley** [bryphe/oni#817]
![screen shot 2017-10-20 at 10 59 46 pm](https://user-images.githubusercontent.com/8421641/31847423-646320ca-b5ea-11e7-9e86-70fbddfa3f88.png)

The scrollbar just doesn't exist in the right window. It works fine in the left window.

Also the cursorline doesn't go to the right window.

There seems to be a ton of weirdness with splits that I can't document right now

**Comment by bryphe** [comment]
Hi @Bretley ,

Thanks for logging the issue! Ya, there were a bunch of issues here - most of them coming from this PR: #805 

The biggest issue was Neovim sends us the windows position as an array of `[row, col]`, but we were treating that was `[x, y]` (which is the opposite), so the measurements were wrong. This broke the buffer scroll bar, the cursor line, and any sort of UI that depends on these measurements (like error squiggles).
