### ISSUE TITLE
Defaults for OSX should allow c-p, c-n to move up down menu.

### ISSUE THREAD

**Issue by jordwalke** [bryphe/oni#822]
It's common for OSX editors, (and chrome even) to allow navigating up/down in modal lists via `c-n`/`c-p`. In Oni, the default keybindings to open the various command pallets in Oni is `c-p`, and `c-shift-p`. This means that once the modals are opened, `c-n` can be used to move down, but `c-p` cannot be used to move up because that's the keybinding for opening the overlay in the first place.

I recommend using the Sublime Text default shortcuts, which have inspired other editors such as VSCode.
[Here's](http://docs.sublimetext.info/en/latest/reference/keyboard_shortcuts_osx.html) the OSX keyboard reference for Sublime, which has the overlay windows opening with command+p, and command+shift+p, so that the menu may be navigated with control+p, control+n for down/up respectively.
<img width="655" alt="screen shot 2017-10-22 at 10 25 50 pm" src="https://user-images.githubusercontent.com/977348/31873510-5e630296-b778-11e7-8bdd-afcd775e30ab.png">

I notice the trend of having `cmd+p`, and `cmd+shift+p` be OSX shortcuts for two types of typeahead overlays, so going by the same pattern in Oni will make people feel instantly comfortable in Oni.

**Comment by bryphe** [comment]
Great point @jordwalke ! Thanks for calling this out, and sharing the Sublime shortcuts. 
This is definitely fits in with the 'ease the learning curve' aspect of Oni.

You're right, `cmd+p` and `cmd+shift+p` better fit the platform. We have a few Mac-specific key bindings already - so it should be straightforward to plug these in there. I'll take a look at this tomorrow.
