### ISSUE TITLE
closing fuzzy file finder popup

### ISSUE THREAD

**Issue by rockneverdies55** [bryphe/oni#829]
Currently it looks like pressing `ESC` is the way to close the fuzzy file search dialog. 

Can you guys also add `Ctrl + {` and/or `Ctrl + C` bindings to that as well ?

**Comment by bryphe** [comment]
Thanks for the suggestion @rockneverdies55 ! 

Agree, this will make it more natural for users accustomed to using `CtrlP` or similiar plugins.

**Comment by jared-skinner** [comment]
I added this feature in #833

**Comment by rockneverdies55** [comment]
Awesome thank you guys. Perhaps the best way to implement this would be closing the popup with user's any ESC key mappings. 

Though this will definitely feel better as it is for me.

**Comment by bryphe** [comment]
Just pulled in #833 - nice work @jared-skinner !
