### ISSUE TITLE
Oni tabs not shown

### ISSUE THREAD

**Issue by hoschi** [bryphe/oni#835]
I normally use my own `init.vim` but also tried it with Oni defaults. I still see tabline from NeoVim and not from Oni. When I create a new tab via `:tabnew` the following errors are logged:
![2017-10-28-165148_1370x1384_scrot](https://user-images.githubusercontent.com/163128/32135482-4b9740a0-bc00-11e7-95bd-96fb2c726136.png)

Oni: b64f415ce05244a9bf2063880602d813833ece8c
Config:
```js
module.exports = {
  "editor.fontSize": "14px",
  //"editor.fontLigatures": true,
  "oni.useDefaultConfig": true,
  "editor.scrollBar.visible": false,
  "editor.quickInfo.enabled": false,
  "editor.cursorLine": false,
  "editor.cursorColumn": false,
  "editor.clipboart.enabled": false,
  "editor.quickInfo.delay": 250,
  //"editor.cursorColumnOpacity": 0.1,
  "tabs.enabled": true,
  "tabs.showVimTabs": true,
}
```

**Comment by bryphe** [comment]
Hi @hoschi ,

I think this might be related to the Neovim version (there was a similiar discussion in #657). Neovim needs to support the `ui-ext-tabline`, it appears that your version may be a bit older.

A quick way to test is to run `:help ui-ext-tabline` - do you see anything for that?

If not, you could try bringing in the latest nightly Neovim release, and see if that works.

**Comment by hoschi** [comment]
![2017-10-31-142840_1370x1384_scrot](https://user-images.githubusercontent.com/163128/32226058-cbaa79d0-be47-11e7-8120-9301c26c2528.png)

I looked into and switched from my own arch package to `neovim` https://www.archlinux.org/packages/community/x86_64/neovim/
.......... where I missread 0.2.0-2 as 0.2.2 which is greater than the version mentioned here
https://github.com/bryphe/oni/issues/579#issuecomment-320982971

sorry :disappointed: I switch to `neovim-git` package then

**Comment by bryphe** [comment]
Sorry, it's confusing for sure! I'm glad it is working now 😄
