### ISSUE TITLE
Oni freezes entirely on python autocompletion

### ISSUE THREAD

**Issue by Bretley** [bryphe/oni#843]
Repro:
![screen shot 2017-10-31 at 5 30 01 pm](https://user-images.githubusercontent.com/8421641/32249956-27783bf8-be61-11e7-99a5-9331207e500c.png)

**Comment by Bretley** [comment]
This breaks oni for me

**Comment by bryphe** [comment]
Thanks for catching this, @Bretley ! It's a regression from some of the completion menu changes.

I'm able to repro this (fortunately or unfortunately it's easy to hit...). Almost have a PR ready.

**Comment by bryphe** [comment]
Fix is in master - let me know if you still see issues after picking it up. Thanks again for finding & logging the issue, @Bretley !
